CREATE TABLE `t_agency_account` (
  `id` bigint(10) NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL COMMENT '用户名(用户邮箱)',
  `password` varchar(100) NOT NULL COMMENT '密码',
  `agency_id` bigint(10) DEFAULT NULL COMMENT '经销商id',
  `email` varchar(100) DEFAULT NULL COMMENT '邮箱',
  `contacts` varchar(50) DEFAULT NULL COMMENT '联系人',
  `telephone` varchar(20) DEFAULT NULL COMMENT '联系人电话',
  `sex` tinyint(4) DEFAULT NULL COMMENT '性别',
  `status` tinyint(4) DEFAULT NULL COMMENT '是否删除状态 1－有效  0－已删除',
  `create_time` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `update_time` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `last_login_time` timestamp NULL DEFAULT NULL COMMENT '上次登录时间',
  `is_edit_valid` tinyint(4) NOT NULL COMMENT '账号是否可以进行报价及其它操作 1-有效 0-无效（即只可登录）',
  `role_id` bigint(10) DEFAULT NULL COMMENT '角色ID',
  PRIMARY KEY (`id`),
  KEY `status_index` (`status`)
) ENGINE=InnoDB AUTO_INCREMENT=694 DEFAULT CHARSET=utf8 COMMENT='经销商帐号表';

CREATE TABLE `t_sale_settlement` (
  `id` bigint(10) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `settlement_no` varchar(30) NOT NULL COMMENT '结算单号',
  `sale_id` bigint(10) NOT NULL COMMENT '销售单ID',
  `settlement_date` datetime(3) NOT NULL COMMENT '结算日期',
  `is_exception` tinyint(1) NOT NULL COMMENT '是否异常结算(1:是，0：否)',
  `exception_id` tinyint(1) DEFAULT NULL COMMENT '异常原因',
  `creator_id` bigint(10) NOT NULL COMMENT '创建人ID',
  `create_date` datetime(3) NOT NULL COMMENT '创建时间',
  `modify_date` datetime(3) DEFAULT NULL COMMENT '修改时间',
  `type` tinyint(1) NOT NULL COMMENT '结算单类型（1：销售结算，2：退车结算，3：退换车结算，4：提前还款）',
  `DEL_pay_info_id` bigint(10) DEFAULT NULL,
  `status` tinyint(1) NOT NULL COMMENT '是否已生成销售结算（1：是，0：否）',
  `modifier_id` bigint(10) DEFAULT NULL COMMENT '修改人ID',
  `total_money` decimal(10,2) DEFAULT NULL COMMENT '应收金额',
  `is_delete` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否删除（1：是，0：否）',
  `vehicle_id` bigint(10) DEFAULT NULL COMMENT '车辆id',
  `frame_no` varchar(50) DEFAULT NULL COMMENT '车架号',
  `dept_id` bigint(10) DEFAULT NULL COMMENT '门店id',
  `member_id` bigint(20) DEFAULT NULL COMMENT '客户ID',
  `member_name` varchar(30) DEFAULT NULL COMMENT '客户姓名',
  `mobile` varchar(30) DEFAULT NULL COMMENT '联系方式',
  `source_no` varchar(30) DEFAULT NULL COMMENT '源单据号',
  `employee_id` bigint(10) DEFAULT NULL COMMENT '销售顾问ID',
  `received_money` decimal(10,2) DEFAULT '0.00' COMMENT '收款金额',
  `should_refund_money` decimal(10,2) DEFAULT '0.00' COMMENT '应退金额',
  `refund_money` decimal(10,2) DEFAULT '0.00' COMMENT '退款金额',
  PRIMARY KEY (`id`),
  UNIQUE KEY `settlement_no` (`settlement_no`) USING BTREE,
  KEY `idx_sale_id` (`sale_id`),
  KEY `idx_source_no` (`source_no`)
) ENGINE=InnoDB AUTO_INCREMENT=200701 DEFAULT CHARSET=utf8 COMMENT='销售结算表';